@{
    Region      = echo North East South West

    Food        = echo Pizza Pancakes Chinese

    Fruit       = echo lemon lime peach apple banana

    Response    = echo Yes No Maybe "Not Sure"

    Ingredients = echo Flour Sugar Salt Milk Eggs Butter

    USCapital   = echo Montgomery Juneau Phoenix Little Rock Sacramento Denver Hartford Dover Washington Tallahassee Atlanta Honolulu Boise Springfield Indianapolis Des Moines Topeka Frankfort Baton Rouge Augusta Annapolis Boston Lansing Saint Paul Jackson Jefferson City Helena Lincoln Carson City Concord Trenton Santa Fe Albany Raleigh Bismarck Columbus Oklahoma City Salem Harrisburg Providence Columbia Pierre Nashville Austin Salt Lake City Montpelier Richmond Olympia Charleston Madison Cheyenne

    President   = echo "George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe", "John Quincy AdamsAndrew Jackson", "Martin Van Buren", "William Henry Harrison", "John Tyler", "James K. Polk", "Zachary Taylor", "Millard Fillmore", "Franklin Pierce", "James Buchanan", "Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant", "Rutherford B. Hayes", "James A. Garfield", "Chester Arthur", "Grover Cleveland", "Benjamin Harrison", "Grover Cleveland", "William McKinley", "Theodore Roosevelt", "William Howard Taft", "Woodrow Wilson", "Warren G. Harding", "Calvin Coolidge", "Herbert Hoover", "Franklin D. Roosevelt", "Harry S. Truman", "Dwight D. Eisenhower", "John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter", "Ronald Reagan", "George Bush", "Bill Clinton", "George W. Bush", "Barack Obama"

     # Louise Hay affirmations
    affirmation = $(
        "Life loves me!"
        "All is well in my world. Everything is working out for my highest good. Out of this situation only good will come. I am safe!"
        "It’s only a thought, and a thought can be changed."
        "The point of power is always in the present moment."
        "Every thought we think is creating our future."
        "I am in the process of positive change."
        "I am comfortable looking in the mirror, saying, 'I love you, I really love you.'"
        "It is safe to look within."
        "I forgive myself and set myself free."
        "As I say yes to life, life says yes to me."
        "I now go beyond other people’s fears and limitations."
        "I am Divinely guided and protected at all times."
        "I claim my power and move beyond all limitations."
        "I trust the process of life."
        "I am deeply fulfilled by all that I do."
        "We are all family, and the planet is our home."
        "As I forgive myself, it becomes easier to forgive others."
        "I am willing to let go."
        "Deep at the center of my being is an infinite well of love."
        "I prosper wherever I turn."
        "I welcome miracles into my life."
        "Whatever I need to know is revealed to me at exactly the right time."
        "I am loved, and I am at peace."
        "My happy thoughts help create my healthy body."
        "Life supports me in every possible way."
        "My day begins and ends with gratitude."
        "I listen with love to my body’s messages."
        "The past is over."
        "Only good can come to me."
        "I am beautiful, and everybody loves me."
        "Everyone I encounter today has my best interests at heart."
        "I always work with and for wonderful people. I love my job."
        "Filling my mind with pleasant thoughts is the quickest road to health."
        "I am healthy, whole, and complete."
        "I am at home in my body."
        "I devote a portion of my time to helping others. It is good for my own health."
        "I am greeted by love wherever I go."
        "Wellness is the natural state of my body. I am in perfect health."
        "I am pain free and totally in sync with life."
        "I am very thankful for all the love in my life. I find it everywhere."
        "I know that old, negative patterns no longer limit me. I let them go with ease."
        "In the infinity of life where I am, all is perfect, whole, and complete."
        "I trust my intuition. I am willing to listen to that still, small voice within."
        "I am willing to ask for help when I need it."
        "I forgive myself for not being perfect."
        "I honor who I am."
        "I attract only healthy relationships. I am always treated well."
        "I do not have to prove myself to anyone."
        "I come from the loving space of my heart, and I know that love opens all doors."
        "I am in harmony with nature."
        "I welcome new ideas."
        "Today, no person, place, or thing can irritate or annoy me. I choose to be at peace."
        "I am safe in the Universe and All Life loves and supports me."
        "I experience love wherever I go."
        "I am willing to change."
        "I drink lots of water to cleanse my body and mind."
        "I choose to see clearly with the eyes of love."
        "I cross all bridges with joy and ease."
        "I release all drama from my life."
        "Loving others is easy when I love and accept myself."
        "I balance my life between work, rest, and play."
        "I return to the basics of life: forgiveness, courage, gratitude, love, and humor."
        "I am in charge, I now take my own power back."
        "My body appreciates how I take care of it."
        "I spend time with positive, energetic people."
        "The more peaceful I am inside, the more peace I have to share with others."
        "Today is a sacred gift from Life."
        "I have the courage to live my dreams."
        "I release all negative thoughts of the past and all worries about the future."
        "I forgive everyone in my past for all perceived wrongs. I release them with love."
        "I only speak positively about those in my world. Negativity has no part in my life."
        "We are all eternal spirit."
        "I act as if I already have what I want - it's an excellent way to attract happiness in my life."
        "I enjoy the foods that are best for my body."
        "My life gets better all the time."
        "It is safe for me to speak up for myself."
        "I live in the paradise of my own creation."
        "Perfect health is my Divine right, and I claim it now."
        "I release all criticism."
        "I am on an ever-changing journey."
        "I am grateful for my healthy body. I love life."
        "Love flows through my body, healing all dis-ease."
        "My income is constantly increasing."
        "My healing is already in process."
        "There is always more to learn."
        "I now live in limitless love, light, and joy."
        "I become more lovable every day."
        "It is now safe for me to release all of my childhood traumas and move into love."
        "I deserve all that is good."
        "I am constantly discovering new ways to improve my health."
        "Love is all there is!"
        "My life gets more fabulous every day."
        "Today I am at peace."
        "Loving others is easy when I love and accept myself."
        "I have the perfect living space."
        "I have compassion for all."
        "I trust the Universe to help me see the good in everything and in everyone."
        "I love my family members just as they are. I do not try to change anyone."
        "There is plenty for everyone, and we bless and prosper each other."
        "I love and approve of myself."
        "Life is good, and so it is!"
    )
}