function country {
    $(
        'Afghanistan'
        'Albania'
        'Algeria'
        'Andorra'
        'Angola'
        'Antigua and Barbuda'
        'Argentina'
        'Armenia'
        'Australia'
        'Austria'
        'Azerbaijan'
        'Bahamas'
        'Bahrain'
        'Bangladesh'
        'Barbados'
        'Belarus'
        'Belgium'
        'Belize'
        'Benin'
        'Bhutan'
        'Bolivia'
        'Bosnia and Herzegovina'
        'Botswana'
        'Brazil'
        'Brunei'
        'Bulgaria'
        'Burkina Faso'
        'Burundi'
        'Cabo Verde'
        'Cambodia'
        'Cameroon'
        'Canada'
        'Central African Republic (CAR)'
        'Chad'
        'Chile'
        'China'
        'Colombia'
        'Comoros'
        "Cote d'Ivoire"
        'Costa Rica'
        'Croatia'
        'Cuba'
        'Cyprus'
        'Czechia'
        'Democratic Republic of the Congo'
        'Ecuador'
        'Egypt'
        'El Salvador'
        'Equatorial Guinea'
        'Eritrea'
        'Estonia'
        'Eswatini (formerly Swaziland)'
        'Ethiopia'
        'Fiji'
        'Finland'
        'France'
        'Gabon'
        'Gambia'
        'Georgia'
        'Germany'
        'Ghana'
        'Greece'
        'Grenada'
        'Guatemala'
        'Guinea-Bissau'
        'Guinea'
        'Guyana'
        'Haiti'
        'Honduras'
        'Hungary'
        'Iceland'
        'India'
        'Indonesia'
        'Iran'
        'Iraq'
        'Ireland'
        'Israel'
        'Italy'
        'Jamaica'
        'Japan'
        'Jordan'
        'Kazakhstan'
        'Kenya'
        'Kiribati'
        'Kosovo'
        'Kuwait'
        'Kyrgyzstan'
        'Laos'
        'Latvia'
        'Lebanon'
        'Lesotho'
        'Liberia'
        'Libya'
        'Liechtenstein'
        'Lithuania'
        'Luxembourg'
        'Madagascar'
        'Malawi'
        'Malaysia'
        'Maldives'
        'Mali'
        'Malta'
        'Marshall Islands'
        'Mauritania'
        'Mauritius'
        'Mexico'
        'Micronesia'
        'Moldova'
        'Monaco'
        'Mongolia'
        'Montenegro'
        'Morocco'
        'Mozambique'
        'Myanmar (formerly Burma)'
        'Namibia'
        'Namibia'
        'Nauru'
        'Nauru'
        'Nepal'
        'Nepal'
        'Netherlands'
        'Netherlands'
        'New Zealand'
        'New Zealand'
        'Nicaragua'
        'Nicaragua'
        'Niger'
        'Niger'
        'Nigeria'
        'Nigeria'
        'North Korea'
        'North Korea'
        'North Macedonia (formerly Macedonia)'
        'North Macedonia (formerly Macedonia)'
        'Norway'
        'Norway'
        'Oman'
        'Pakistan'
        'Palau'
        'Palestine'
        'Panama'
        'Papua New Guinea'
        'Paraguay'
        'Peru'
        'Philippines'
        'Poland'
        'Portugal'
        'Qatar'
        'Republic of the Congo'
        'Romania'
        'Russia'
        'Rwanda'
        'Saint Kitts and Nevis'
        'Saint Lucia'
        'Saint Vincent and the Grenadines'
        'Samoa'
        'San Marino'
        'Sao Tome and Principe'
        'Saudi Arabia'
        'Senegal'
        'Serbia'
        'Seychelles'
        'Sierra Leone'
        'Singapore'
        'Slovakia'
        'Slovenia'
        'Solomon Islands'
        'Somalia'
        'South Africa'
        'South Korea'
        'South Sudan'
        'Spain'
        'Sri Lanka'
        'Sudan'
        'Suriname'
        'Sweden'
        'Switzerland'
        'Syria'
        'Taiwan'
        'Tajikistan'
        'Tanzania'
        'Thailand'
        'Timor-Leste'
        'Togo'
        'Tonga'
        'Trinidad and Tobago'
        'Tunisia'
        'Turkey'
        'Turkmenistan'
        'Tuvalu'
        'Uganda'
        'Uganda'
        'Ukraine'
        'Ukraine'
        'United Arab Emirates (UAE)'
        'United Arab Emirates (UAE)'
        'United Kingdom (UK)'
        'United Kingdom (UK)'
        'United States of America (USA)'
        'United States of America (USA)'
        'Uruguay'
        'Uruguay'
        'Uzbekistan'
        'Uzbekistan'
        'Yemen'
        'Zambia'
        'Zimbabwe'
    ) | Get-Random
}