function Job {
    $(
      'Account executive'
      'Account manager'
      'Actor'
      'Actuary'
      'Administrative assistant'
      'Admissions representative'
      'Aerospace engineer'
      'Agriculture teacher'
      'Agriculture'
      'Animal control officer'
      'Animal geneticist'
      'Animal nutritionist'
      'Animal science'
      'Animal shelter manager'
      'Animal sitter'
      'Aquatic ecologist'
      'Architect'
      'Art director'
      'Assistant buyer'
      'Assistant professor'
      'B2B sales specialist'
      'Bank teller'
      'Barber'
      'Beautician'
      'Beekeeper'
      'Biochemist'
      'Biological engineer'
      'Biologist'
      'Brand manager'
      'Breeder'
      'Budget analyst'
      'Business development manager'
      'Business intelligence developer'
      'Business reporter'
      'Business teacher'
      'Business'
      'Call center agent'
      'Caregiver'
      'Cashier'
      'Chemical engineer'
      'Chief of operations'
      'Chief operations officer'
      'Civil engineer'
      'Client services coordinator'
      'Client services manager'
      'Collection agent'
      'College professor'
      'Compensation advisor'
      'Compensations and benefits manager'
      'Compliance engineer'
      'Computer programmer'
      'Concierge'
      'Conservationist'
      'Content marketing manager'
      'Continuous improvement lead'
      'Cosmetology instructor'
      'Cosmetology'
      'Cost estimator'
      'Creative director'
      'Creative'
      'Credit analyst'
      'Customer care associate'
      'Customer service manager'
      'Customer service'
      'Dancer'
      'Data architect'
      'Database manager'
      'Demand generation director'
      'Dental assistant'
      'Dental hygienist'
      'Dentist'
      'Dietitian'
      'Director'
      'Distribution supervisor'
      'Doctor'
      'Editor'
      'Education'
      'Electrical engineer'
      'Electrologist'
      'Engineering'
      'English teacher'
      'Environmental engineer'
      'Esthetician'
      'Executive recruiter'
      'Executive'
      'Farmer'
      'Fashion designer'
      'Fashion show stylist'
      'Finance'
      'Financial advisor'
      'Financial auditor'
      'Financial manager'
      'Financial planner'
      'Financial services representative'
      'Floral designer'
      'Food scientist'
      'Foresters'
      'Front desk coordinator'
      'Front-end web developer'
      'Geological engineer'
      'Graphic designer'
      'Groomer'
      'Guidance counselor'
      'Hairdresser'
      'Healthcare'
      'Help desk assistant'
      'Horticulturist'
      'Hospitality'
      'Human resources assistant'
      'Human resources consultant'
      'Human resources director'
      'Human resources generalist'
      'Human resources manager'
      'Human resources specialist'
      'Human resources systems administrator'
      'Human resources'
      'Illustrator'
      'Information security analyst'
      'Information technology'
      'Instructional designer'
      'Insurance sales agent'
      'International human resources associate'
      'Investment banking analyst'
      'IT manager'
      'Java developer'
      'Kennel attendant'
      'Labor relations specialist'
      'Leadership'
      'Librarian'
      'Loan officer'
      'Logistics coordinator'
      'Makeup artist'
      'Manager'
      'Marine engineer'
      'Marketing analyst'
      'Marketing assistant'
      'Marketing consultant'
      'Marketing coordinator'
      'Marketing director'
      'Marketing manager'
      'Marketing'
      'Math teacher'
      'Mechanical engineer'
      'Message therapist'
      'Mobile application developer'
      'Multimedia animator'
      'Nail technician'
      'Nuclear engineer'
      'Nurse'
      'Occupational therapy aide'
      'Office clerk'
      'Office manager'
      'Operations assistant'
      'Operations manager'
      'Operations'
      'Orthodontist'
      'Painter'
      'Personal trainer'
      'Pet walker'
      'Petroleum engineer'
      'Pharmacist'
      'Pharmacy assistant'
      'Physical therapist'
      'Plant biologist'
      'Plant nursery attendant'
      'President'
      'Principal'
      'Producer'
      'Product engineer'
      'Product marketing manager'
      'Project manager'
      'Public relations specialist'
      'Real estate broker'
      'Regional sales manager'
      'Retail sales associate'
      'Retail salesperson'
      'Safety engineer'
      'Sales analyst'
      'Sales associate'
      'Sales consultant'
      'Sales director'
      'Sales manager'
      'Sales representative'
      'Sales'
      'Salon manager'
      'Science teacher'
      'Scrum master'
      'Search engine optimization specialist'
      'Senior process engineer'
      'Service advisor'
      'Singer'
      'Skin care specialist'
      'Social media coordinator'
      'Social media manager'
      'Software developer'
      'Software engineer'
      'Soil and plant scientist'
      'Spa manager'
      'SQL developer'
      'Store manager'
      'Substitute teacher'
      'Superintendent'
      'Supervisor'
      'Supply chain coordinator'
      'Supply chain specialist'
      'Surgical technologist'
      'Talent acquisition coordinator'
      'Tattoo artist'
      'Team lead'
      'Team leader'
      'Technical support representative'
      'Telemarketer'
      'Test administrator'
      'Test scorer'
      'Training and development manager'
      'Travel nurse'
      'Tutor'
      'UI developer'
      'UX designer'
      'Veterinarian'
      'Veterinary assistant'
      'Veterinary ophthalmologis'
      'Veterinary pathologist'
      'Vice President'
      'Vice principal'
      'Virtual assistant'
      'Warehouse supervisor'
      'Web administrator'
      'Web developer'
      'Wedding stylist'
      'Wildlife biologist'
      'Wildlife inspector'
      'Wildlife rehabilitator'
      'Writer'
      'Zoologist'
    ) | Get-Random
}
