function Werk {
  $(
    'Advokaat'
    'Kreatiewe Direkteur'
    'Elektriese Ingenieur'
    'Actuur'
    'Onderweiser'
    'Dokter'
    'Slagter'
    'Argitek'
    'Skoen Maker'
    'Bokser'
    'Opsigter'
    'Kok'
    'Beeswagter'
    'Brandweerman'
    'Visserman'
    'Sokerspeler'
    'Regter'
    'Tuinier'
    'Jagter'
    'Polisieman'
    'Loodgieter'
    'Onderwyseres'
    'Chirug'
    'Kelnerin'
    'Non'
    'Fotograaf'
    'Vensterwasser'
    'Rekenaar Wetenskaplike'
    'Maratonatleet'
    'Musikant'
    'Landros'
    'Kajaker'
  ) | Get-Random
}
